### PR TITLE
Added reference to "Moonwalking with Einstein".

### PR DESCRIPTION
**Pull request by DataWookie**
Sitting in instructor training in Cape Town. I just read this book and thought that it was relevant to the "Expertise and Memory" session.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
Thanks Andrew!  This looks good to me.  @ErinBecker ?

**Comment by ErinBecker** [comment]
Thanks @DataWookie!

**Comment by raynamharris** [comment]
Thanks for this suggestion. I checked this book out from the library and I'm already halfway through reading it. So good!

**Comment by DataWookie** [comment]
Great. It's a really good read. I learned some interesting tricks (?) too, some of which I have put into practice.

**Pull request merged**
