### PR TITLE
Moving all links into a single included `links.md` file.

### PR DESCRIPTION
**Pull request by gvwilson**
**This does *not* work yet.**  In order for it to do so, the links must be at the bottom of the file, but our layout has keypoints after it in episodes, so the link table is rendered as text.  See http://swcarpentry.github.io/managing-research-software-projects for an example where it *does* seem to work.

### CODE REVIEW

**Comment by rgaiacs** [comment]
@gvwilson https://github.com/gvwilson/instructor-training/pull/3 should fix the problem that you have. :-)

**Comment by gvwilson** [comment]
That's really all it was???

**Comment by rgaiacs** [comment]
@gvwilson This has some conflicts. I don't know who should pick this one.

**Comment by ChristinaLK** [comment]
@rgaiacs is this worth pursuing or should we just close this?

**Comment by ErinBecker** [comment]
Closed due to lack of activity. If there is desire for this index, please update.

**Pull request closed without merging**
