### PR TITLE
Update instructors.md

### PR DESCRIPTION
**Pull request by raynamharris**
Added Rayna's testimonial

### CODE REVIEW

**Comment by alistairwalsh** [comment]
I really like the bit about SWC making you a better collaborator. I feel that too but hadn't realised it until you articulated it.

**Comment by raynamharris** [comment]
Thanks @alistairwalsh. It is a nice unanticipate perk!

**Comment by gvwilson** [comment]
People show up to help with political campaigns because they believe in the cause. They stick around because the people they've been putting up posters with and knocking on doors with and stuffing envelopes with have become family.

*sniff*

I love you guys.  S'rsly.  "Should oooold acquaintance beeee forgot..." *hic*

**Comment by weaverbel** [comment]
Thanks for the <3 @gvwilson AKA The Big Softie ;-)

**Pull request merged**
