### PR TITLE
Update checkout.md

### PR DESCRIPTION
**Pull request by raynamharris**
Added the new pick one of three options for contributing to our lessons. 

I'm not sure how much of the information about proposing new changes should stay and what should go.  Any suggestions before I start cuttings?

### CODE REVIEW

**Comment by gvwilson** [comment]
thanks

**Comment by ErinBecker** [comment]
Thanks Rayna. Just a quick question. Is the following meant to apply in both directions (i.e. can DC instructors qualify by submitting a change to SWC lesson?)?

>Note that you may submit a change to a Data Carpentry lesson when qualifying as a Software Carpentry instructor: the goal is to be sure you are familiar with the process.

I assume the answer is yes. If so, can we add a "and vice versa" just to stave off confusion?

Thanks again!

**Comment by raynamharris** [comment]
@ErinBecker yes, the wording should be vice versa, to the best of my knowledge

**Comment by ErinBecker** [comment]
This contradicts what Greg said in training today, so lets make sure all
are on the same page.

What was said in training was that DC instructors need to contribute to a
DC lesson and do lesson demo on DC materials. Vice versa for swc
instructors and that anyone who wanted to get double certified needs to do
both of those twice.

Would be good to clarify so we are all communicating the same thing.

**Comment by raynamharris** [comment]
Thanks @ErinBecker . See new PR #225

**Pull request merged**
