### PR TITLE
remove "two day" from DC description (it's not a difference)

### PR DESCRIPTION
**Pull request by maneesha**
---

### CODE REVIEW

**Comment by maneesha** [comment]
Following venn diagram image should also be fixed accordingly.

**Comment by raynamharris** [comment]
I'm not sure who created the venn diagram. This particular venn diagram point is making that DC cirriculum is centered around a single dataset and the SWC is modular. I think if we keep the existing Venn it will be fine for now, unless someone wants to completely revamp. it. 

https://github.com/swcarpentry/instructor-training/blob/gh-pages/_episodes/21-carpentries.md

**Comment by ErinBecker** [comment]
I've always interpreted this the way @raynamharris mentioned - that it's a pointer towards the SWC materials being modular while the DC materials are meant to be used as a full set (for a particular workshop type).

**Comment by ChristinaLK** [comment]
So is it okay as is?  I think I'm the original creator of that one.

**Comment by maneesha** [comment]
I agree as @ErinBecker said above, we should make clear that the  SWC materials are  modular while the DC materials are meant to be used as a full set.

I don't want us to explicitly list the fact that it's a *two day* workshop as a *difference*  --- since SWC and DC workshops are both two days that may cause confusion.

**Pull request merged**
