### PR TITLE
adds closed captioning to instructor notes

### PR DESCRIPTION
**Pull request by raynamharris**
Addresses issue https://github.com/swcarpentry/instructor-training/issues/414, at least in the instructor notes

### CODE REVIEW

**Comment by maneesha** [comment]
I'm seeing this a little late.  I want to revert this PR merge.   The "live coding done poorly" does *not* have a closed captioning option.  The "live coding done right" does have a closed caption option but it is not an accurate transcription. It uses Youtube or Google's speech recognition so it does not do well with accents, jargon, or background noise.  I watched the first 60 seconds of the "done right" one with no sound, closed captioning only, and it made no sense.

I would rather not  recommend this rather than recommend something that produces basically jibberish.

**Comment by lexnederbragt** [comment]
We can add our own closed captioning, apparently: https://support.google.com/youtube/answer/2734796?hl=en

**Comment by maneesha** [comment]
@lexnederbragt  - yes we can but it is a lot of work to transcribe everything.  If we find someone who's willing to do it I am all for it.

**Comment by ChristinaLK** [comment]
Should we email discuss and see if anyone is interested?

**Comment by ErinBecker** [comment]
@ChristinaLK that sounds like a great idea. Would you like to write the email? Or maybe @maneesha? I've reverted the PR.

**Comment by lexnederbragt** [comment]
As the main actor, director and producer of the videos :-) I'm OK with sending that email.

**Comment by ErinBecker** [comment]
Great, thanks @lexnederbragt

**Pull request merged**
