### PR TITLE
Revamping schedule

### LINKED ISSUE #38: Incorporate schedule from Manchester
notes/manchester.txt describes a recent successful workshop - fold that into a reorganization of this material (including a schedule).

### PR DESCRIPTION
**Pull request by gvwilson**
This more-or-less corresponds to UW, with some Davis and Oklahoma mixed in.

@arokem @apawlik @ChristinaLK can you all please review?

This closes #38.

### CODE REVIEW

**Comment by arokem** [comment]
I agree that it was hard to fit everything in, but am sad to see discussions of memory and cognitive load being left by the wayside. 

One tweak I would propose is to move discussion on motivators/demotivators to later in the day, replacing that with the workshop website exercise. That's because I think that the website exercise is relatively demanding, and the motivation discussion is the kind of thing to wake up a snoozing audience on the second afternoon.

**Comment by arokem** [comment]
In particular, I gave way to little time for the video exercise at UW. An hour is very appropriate.

**Comment by gvwilson** [comment]
Happy to put it back in - what can we shrink or cut to make room?

**Comment by gvwilson** [comment]
Are you proposing swapping the motivation stuff with building a workshop 
website?

**Comment by gvwilson** [comment]
Are the current timings OK?

**Comment by arokem** [comment]
Yes. Swap motivation with building a workshop website.

The timings seem fine. I wonder whether learning objectives can be condensed to fit something about cognitive load. The faded example, and the ideas around cognitive load (e.g. 7+/-2) seemed to be one of the favorites at the UW training. Maybe that could be incorporated into the bit about mental models and concept maps somehow?

**Comment by gvwilson** [comment]
On 2016-03-20 4:09 PM, Ariel Rokem wrote:
>
> Yes. Swap motivation with building a workshop website.
>
Done.

> The timings seem fine. I wonder whether learning objectives can be 
> condensed to fit something about cognitive load. The faded example, 
> and the ideas around cognitive load (e.g. 7+/-2) seemed to be one of 
> the favorites at the UW training. Maybe that could be incorporated 
> into the bit about mental models and concept maps somehow?
>
Suggestions welcome.
G

**Comment by raynamharris** [comment]
+1 I definitely like how clean the revamped schedule looks. 

I would like to compare the current workflow to the instructor training course I took at UC Davis in January 2016, but I can't seem to find that repo.  Any idea where that is?

**Comment by gvwilson** [comment]
Jan 2015?

**Comment by raynamharris** [comment]
Sorry, yes, Jan 2015.

**Comment by gvwilson** [comment]
I don't think there was a website for that one... At least, there's 
nothing in AMY.

**Comment by raynamharris** [comment]
No worries. Thanks for checking.

**Pull request merged**
