### PR TITLE
Moving overview of existing lesson materials to Carpentries lesson.

### PR DESCRIPTION
**Pull request by gvwilson**
Based on discussion with @ErinBecker.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
can this wait to be merged until after the Oslo training?

**Comment by ErinBecker** [comment]
@ChristinaLK I think the plan was to do this after Oslo. @gvwilson Can you confirm?

**Comment by gvwilson** [comment]
Yup - might merge between Oslo and SciPy, but that depends on thumbs-up.

**Comment by ErinBecker** [comment]
This reorganization looks good to me. I think having the description of content when we introduce the organizations will be good.

**Comment by ChristinaLK** [comment]
See another take on this in #256

**Pull request merged**
