### PR TITLE
Fix missing and spurious references

### PR DESCRIPTION
**Pull request by andreabedini**
Some references were missing and some were spurious. I used the script below to check. Perhaps it could be included into `lesson_check.py`.

``` python
import re
from collections import defaultdict, namedtuple
from glob import glob

re_refs = re.compile('\]\[([a-z-]+)\]', flags=re.M)
re_defs = re.compile('^\[([a-z-]+)\]:\s*(.*)', flags=re.M)

fns = glob('_episodes/*.md')

def get_file_refs(fn):
    text = open(fn).read()
    return set(re_refs.findall(text))

def get_file_defs(fn):
    text = open(fn).read()
    return dict(re_defs.findall(text))

file_refs = {fn: get_file_refs(fn) for fn in fns}
file_defs = {fn: get_file_defs(fn) for fn in fns}

Suggestion = namedtuple('Suggestion', ['file', 'url'])
reverse_index = defaultdict(list)
for fn, refs in file_defs.items():
    if not refs: continue
    for key, url in refs.items():
        reverse_index[key].append(Suggestion(fn, url))

for fn in fns:
    defined_keys = set(file_defs[fn].keys())
    missing = file_refs[fn] - defined_keys
    spurious = defined_keys - file_refs[fn]

    if missing or spurious:
        print('\nFound issues with', fn)

    for ref in missing:
        print("Missing reference", ref)
        for suggestion in reverse_index[ref]:
            print('Suggestion for', ref, suggestion.url, 'as defined in', suggestion.file)

    if spurious:
        print("Spurious references", ', '.join(spurious))

```

### CODE REVIEW

**Comment by gvwilson** [comment]
Nice - can you please fold this into `bin/lesson_check.py` (which uses the AST rather than the raw text)?

**Comment by andreabedini** [comment]
Yes, will try.

**Comment by andreabedini** [comment]
The script above has to be almost entirely rewritten to use the AST like done in `lesson_check.py`. Skimming the code it's not clear (to me) how the existing checks work or how to implement a new one.

**Comment by gvwilson** [comment]
Any update on this one?

**Comment by gvwilson** [comment]
ping

**Comment by andreabedini** [comment]
@gvwilson I will give it another shot next week.

**Comment by andreabedini** [comment]
@gvwilson you already implemented this in cebd8558273a274f84b3b129c627f42a2ed09ef1 😞

**Pull request closed without merging**
