### PR TITLE
Bringing in material on introductions from @tracykteal

### PR DESCRIPTION
**Pull request by gvwilson**
1.  Import material on introductions from <https://github.com/tracykteal/instructors-introduction>.
2.  Move prose from `README.md` to `_extras/introductions.md`.
3.  Move slides to `files/intro-slides/*.*`.

### CODE REVIEW

**Comment by kcranston** [comment]
I like this material, but I have a question about permissions. The text says this lesson is based on http://www.cmu.edu/teaching/designteach/teach/firstday.html. I don't see a permissive license for that material, just a copyright notice at the bottom. Do we have permission to adapt and release as CC-BY?

**Comment by ErinBecker** [comment]
@kcranston Thanks for the conscientiousness. I wrote to the CMU teaching center to check on permissions and will wait back to see what they say.

**Comment by tracykteal** [comment]
Thanks for checking @ErinBecker. I also had comments on the slides that there's too much text, and I definitely agree. So if we're going to use them as slides, we might pare down text.

**Comment by tracykteal** [comment]
If we have permission, we can bring in as is though, and then update.

**Comment by ErinBecker** [comment]
From Michelle Pierson at CMU:

We grant permission, please use one of the citations below:

Content on our website (www.cmu.edu/teaching) was significantly revised in 2008 and continues to be revised yearly. When referencing or adapting this content, please use the copyright information or the "adapted from..." language provided below:
 
1. When using content as is, please use the copyright information:
© Copyright 2008, 2015, Eberly Center for Teaching Excellence & Educational Innovation, Carnegie Mellon University.
 
2. When adapting information, please use this language:
Adapted from: Eberly Center for Teaching Excellence & Educational Innovation, Retrieved [date you accessed the website], www.cmu.edu/teaching/

**Comment by ErinBecker** [comment]
@tracykteal Could you please adapt the language to use that above and I'll put the PR through?

**Pull request merged**
