### PR TITLE
Create welcome episode 00-welcome.md 

### PR DESCRIPTION
**Pull request by raynamharris**
First attempt to address [issue #231](https://github.com/swcarpentry/instructor-training/issues/231) on adding a welcome episode. 

These are the first three multiple questions that come to mind. A variation of the 2nd is part of the post-workshop questionnaire. I'm open to adding more or rewording these or any other suggestions. 

Also, I call this lesson 00, but it could be 01, especially if the current episode one is moved to later.

### CODE REVIEW

**Comment by ErinBecker** [comment]
I like this and think it gives a good (short) contextual background for the whole 2 day event. I specifically like how you used a question about making MCQ questions - good lead in for first section of content.

**Comment by ErinBecker** [comment]
Playing around with the idea of changing the answer options for the three mcqs so that they match our guidelines for good mcq questions. :-) Maybe not necessary.

**Comment by raynamharris** [comment]
I think the question should definitely match our guidelines for good mcq questions :)

**Comment by ErinBecker** [comment]
Or we can use it after the fact as an example of what not to do and ask them to improve it for the exercise? I know we already have them writing an MCQ question, improving one would be faster than writing from scratch, but wouldn't give them the prep for the teaching demo it's currently tied to.

**Comment by ErinBecker** [comment]
@raynamharris What do you think of adding an MCQ asking about their previous experience teaching? This could either take the total up to 4 MCQs or replace the one about live coding. Would it be useful for us to know if the trainees are coming in with previous teaching experience and/or highly ingrained ideas about teaching?

**Comment by raynamharris** [comment]
@ErinBecker let's go ahead an add one. Once all four are there, we can decide if one question should be cut or it the live coding question can be interviewed into the general previous teaching question

**Comment by ErinBecker** [comment]
@raynamharris - I added a question, but am a little worried that the order of options will imply a hierarchy with respect to university vs. K12 teaching. Any ideas?

**Comment by raynamharris** [comment]
@ErinBecker If the distinction between K-12 or university is not important, you could merge A and B to say something like "The lead instructor for a year- or semester-long course", which would distinguish them from being a teaching assistant or teaching short workshops. I do sorta see the hierarchy there, but it doesn't bother me. You could totally mix it up (say C, E, D, A, B)

**Comment by ErinBecker** [comment]
@raynamharris I think it's important for us to know whether they have K12 teaching or university teaching experience. If they've taught K12 they've had formal pedagogical training and likely practice-based training, so are more likely to be on board with the curriculum. We could potential use folks like this as resources during the training (e.g. pair them up strategically). 

When I was doing graduate TA training, there were two TAs in the group who had taught K12. They were fantastic resources and very useful for helping get others "bought-in" to the idea of practice-based teaching.

**Comment by gvwilson** [comment]
I like where this is going - please merge as soon as you're both happy with wording, and thank you.

**Comment by ErinBecker** [comment]
I'm happy with it!

**Pull request merged**
