### PR TITLE
change Home to icon, move License to footer and squash searchbar

### PR DESCRIPTION
**Pull request by tomliversidge**
This will 

- change the text "Home" to a home icon
- move "License" menu item to footer
- shrink the width of the searchbar

### CODE REVIEW

**Comment by tomliversidge** [comment]
capture2

**Comment by tomliversidge** [comment]
capture

**Comment by gvwilson** [comment]
Thanks for the PR - happy to shrink the width of the searchbar, might be 
allowed to change "Home" to an icon, but "License" will have to stay in 
the top menu (our lessons being CC licensed is a big part of our pitch).

Cheers,

Greg

**Comment by tomliversidge** [comment]
Ok. Can any of the non- drop down menu items either go in an existing drop down or be grouped into a new one? I.e could License and Code of conduct be grouped together into a new drop down?

Or can everything be made smaller? And with less gaps between...

Trying to think of ways to save space!

**Comment by gvwilson** [comment]
Sticking with existing layout.

**Pull request closed without merging**
