### PR TITLE
added google form version of red/green stickies

### PR DESCRIPTION
**Pull request by raynamharris**
@ChristinaLK I'm officially suggesting that we add this to the curriculums. I'm so glad you made the original one :)

### CODE REVIEW

**Comment by ChristinaLK** [comment]
I forgot about this!  Glad it's been useful.  :)

I think this change is a good one -- will leave it open for more comments but will check in and merge later this week if no one else does.

**Comment by lexnederbragt** [comment]
+1. But:

>Make a copy of this one and change the name to that of your workshop

 I couldn't make a copy. Can you try to enable editing of the form? I think that solves it.

**Comment by raynamharris** [comment]
@lexnederbragt I've enabled editing, so you should be able to use it. 

The data collected in my most recent workshop was incredibly useful!!! They students had very positive reactions to our openness to critique and ability to change our behavior to accomodate suggestions for improvement.

**Comment by lexnederbragt** [comment]
When I go to the form I can't see an edit link, but maybe that is also not the way to do it. Is there a link that according to google allows others to edit?

Not sure what is an easy way to achieve what we want - I'm still hoping for a system where you write questions in markdown and get them rendered as a fully working questionnaire online. One alternative is to sharing through Socrative for this form as well...

**Comment by raynamharris** [comment]
Hi @lexnederbragt. No, you don't want to edit the form... you want to make a copy. You click the three dots up at the top and select make a copy. This will create your own and give you immediate access to all the responses, which you can share with co-teachers and other instructors/staff by adding collaborators.  
screen shot 2017-03-14 at 9 18 46 pm

I'm not opposed to Socrative, I just never use it.

**Comment by lexnederbragt** [comment]
Here is a screenshot of what the form looks like in my browser(s). No three dots... :-(
And I am logged into google, so it's not that.

image

**Comment by ChristinaLK** [comment]
I think you have to actually give people edit rights for them to copy the form.  :P  Would it be better to have instructions of how to create the form from scratch?  Or a shared copy in Google Drive?  Will make an issue about that latter idea...

**Comment by jduckles** [comment]
It would be great to have all of this information in one place. To do that we could integrate this into the workshop website and pre-populate the "workshop slug" as we have for pre and post-workshop survey links.

An example (filling in the Red sticky note text field) [Click here](https://docs.google.com/forms/d/e/1FAIpQLSd9pqNGTkEY0efaHtjOei1hsJGz8_kLrbqUt0ouug8sPExK4g/viewform?c=0&w=1&entry.1999931699=2017-03-18-someworkshop)


In the workshop template we could add a "feedback" page or link which redirects to the google form with the workshop field filled already. We just use the site.github.project-title Jekyll variable to fill in a unique value for the workshop name. 
```
https://docs.google.com/forms/d/e/1FAIpQLSd9pqNGTkEY0efaHtjOei1hsJGz8_kLrbqUt0ouug8sPExK4g/viewform?c=0&w=1&entry.1999931699={{ site.github.project_title }}
```

**Comment by jduckles** [comment]
The next step would be to get the results to the instructor after the workshop.

**Comment by raynamharris** [comment]
Thanks for the suggestions @ChristinaLK and @jduckles.

I agree that it would be nice to have these all in one centralized location for easy access and to facilitate  meta analyses over time. However, the instructors **must** be able to see this in real-time **during** the workshop. If we have to wait til after the workshop to get the results then we won't be able to adapt the workshop to the learners needs.

**Comment by raynamharris** [comment]
Ah, I now see @ChristinaLK's new Google Drive issue, so I'll close this now as Issue https://github.com/swcarpentry/instructor-training/issues/405 will take care of this

**Pull request closed without merging**
