### PR TITLE
Removing unused exercises

### PR DESCRIPTION
**Pull request by ChristinaLK**
Addresses #229 

This is completely based on what *I* do - if I've removed an exercise that you have consistently used, please comment and I'll put it back in. 

I'm also converting "challenges" that are really discussions to the "discussion" style.

### CODE REVIEW

**Comment by raynamharris** [comment]
Thanks @ChristinaLK !  I agree almost completely!

In episodes/18-motivation.md, I like to say on of the things you've suggested deleting: 
"We all have a different motivation for teaching, and that is a really good thing! SWC wants instructors with diverse backgrounds because you each bring something unique to our community. Read the [testimonials]({{ site.github.url }}/guide/#testimonials) from other instructors, to see what motivates them to teach. **After this course*** Write a short explanation of what motivates you to teach. Save this as part of your teaching philosophy for future reference."

I agree that this shouldn't be a challenge, but I would like to keep the prose in the lesson in some form or other.

**Comment by ChristinaLK** [comment]
I agree!  I actually incorporated it into a callout above, but I like the idea of separating the exercise and making it "for later."

**Comment by ChristinaLK** [comment]
Wait to merge until #238 is addressed.

**Comment by ChristinaLK** [comment]
If there are no other comments, this should be ready to merge.

**Pull request merged**
