### PR TITLE
One more demotivator

### PR DESCRIPTION
**Pull request by arokem**

### CODE REVIEW

**Comment by arokem** [comment]
Note that the first commit contains the interesting stuff: https://github.com/arokem/instructor-training/commit/0e77a7337c6ccfb7ade31b81300eeb9f4606fbd8

Whereas the second one is my text-editor cleaning up errant white-space (I don't know how to stop it from doing that...).

**Comment by karinlag** [comment]
On 02.03.2016 21:39, Ariel Rokem wrote:
> Note that the first commit contains the interesting stuff:
> arokem@0e77a73
> <https://github.com/arokem/instructor-training/commit/0e77a7337c6ccfb7ade31b81300eeb9f4606fbd8>
>
> Whereas the second one is my text-editor cleaning up errant white-space
> (I don't know how to stop it from doing that...).

....which editor is that? Sounds useful!

karin

**Comment by arokem** [comment]
atom!

**Comment by karinlag** [comment]
On 04/03/16 06:36, Ariel Rokem wrote:
> atom!

multiplatform...will have to check it out, thanks!

karin

**Comment by ChristinaLK** [comment]
+1 to merge.  :)

**Pull request merged**
