### PR TITLE
Added checklist for teaching demos

### PR DESCRIPTION
**Pull request by lexnederbragt**

### CODE REVIEW

**Comment by raynamharris** [comment]
Thanks @lexnederbragt , but I'm confused about where this rubric will appear... Why is it under files? Could this be an "extra" document that is accessible via the pull down menu? 

I would like to have one rubric (that is maybe a combo of your's and Christina's) that everyone uses in the demo session. And, we can possible point the students to it before or after they live code so they know what our expectations are.

**Comment by lexnederbragt** [comment]
The teaching-demo-rubric.md file is meant to be printed, hence a separate file. Not sure whether it is desirable to have it accessible via the pull down menu. 

I had meant it to include @ChristinaLK's rubric too - happy to incorporate changes if you feel I didn't succeed  :-)

**Comment by raynamharris** [comment]
@lexnederbragt Cool.  I've signed up to host one demo session a month for the next 4 months. This will be useful.

**Comment by raynamharris** [comment]
Okay to merge?

**Pull request merged**
