### PR TITLE
Move watching the live coding videos before top 10

### PR DESCRIPTION
**Pull request by lexnederbragt**
I suggest to first watch the two videos, collect and discuss feedback on them, and only *then* go over the top 10. Hopefully most of the items will have been treated by then.

### CODE REVIEW

**Comment by ChristinaLK** [comment]
I would also suggest moving these *before* the discussion of live coding advantages/challenges - then people have more of a context for answering these questions.

**Comment by lexnederbragt** [comment]
>I would also suggest moving these before the discussion of live coding advantages/challenges - then people have more of a context for answering these questions.

I don't agree. The discussion on (dis)advantages for instructors and learners sets the stage very well, and generates the necessary context for interpreting the videos.

**Comment by ChristinaLK** [comment]
Having seen it in person, it worked the way you have it now.  
I think I just want to make sure that people know what live coding *is* so they can come up with realistic advantages/challenges.  But if you define live coding at the start and make sure that's clear to everyone, then you could go straight into advantages/disadvantages.

**Comment by ChristinaLK** [comment]
I'd like to merge this - @gvwilson, can I steal it and do so?

**Comment by gvwilson** [comment]
@ChristinaLK please go ahead and merge.

**Pull request merged**
