### PR TITLE
adding beginning of outline for trainees to use during sessions

### PR DESCRIPTION
**Pull request by ChristinaLK**
Still needs revision - comments welcome!

Addressing point 6 in issue #83

### CODE REVIEW

**Comment by gvwilson** [comment]
Is this consistent with the revised schedule?  Do you see this being pasted into the Etherpad at the start of training, or should it be incorporated into messages/welcome.txt?

**Comment by ChristinaLK** [comment]
I organized by topic, not schedule, as I was thinking of this more as `messages/outline.txt` document, than something to be pasted into the etherpad.  One of the points raised by @apawlik was the potential need for a notes platform besides the etherpad.   

It's also a nice "meta" for the idea of handouts in an actual SWC workshop.  :)

**Comment by ChristinaLK** [comment]
Can @apawlik take a look at this?  Was this what you had in mind, in terms of a handout?

**Comment by apawlik** [comment]
Thanks for this. Looks good - we may add a few more things in due course.

Yes, I thought about something like this in terms of a hand-out. Based on the feedback that I get and the observation from lots of workshops, I will strongly advocate for a handout that could be printed out and given to people. **Lots** of people take notes during the IT in their notebooks and often say that having a  handout on which they could take notes would be useful.
**It doesn't matter** that we have materials online. People want a handout. I think the fact that *some* of us (trainers) rely 100% on electronic notes doesn't mean we have to force trainees to do so.
Etherpad is also not great - it's a MESS half-way through the workshop.

**Comment by ChristinaLK** [comment]
@apawlik, I agree that a handout like this (that people can fill in + annotate) is a good idea.  Ideally then, this should be a pdf.  Suggestions for how to make that happen?  @gvwilson?

Also, Aleksandra, any comments on format or content?  I tried to pull major terms from each section, but didn't explicitly list things like "faded examples" or "multiple choice questions" - I thought people could write them in under the "teaching tools" item in each section.  Does that make sense?  Do you think learners will think that way?  Does it matter?

**Comment by gvwilson** [comment]
If y'all can create the content, I can take care of PDF'ing.

**Comment by ChristinaLK** [comment]
Finally picking this back up again - I moved into `messages`.  If it can be pdf'd, that'd be great.  I'll definitely try to use this in June + let you know how it goes.

**Pull request merged**
